### ISSUE TITLE
请教一下关于 DeskMini 110 中核显随机死机问题

### ISSUE THREAD

**Issue by ghost** [shum-elli/deskmini110-qnct-hackintosh-efi#1]
老哥你好呀，最近最第一次用 DeskMini 110 安装黑苹果以前也没弄过没经验，结果遇到了随机定格死机问题，给我整烦了🤣，正好看到老哥配置跟我的差不多，就想请教一下老哥安装黑苹果的时候有没有遇到这个问题。

* 但如果驱动了 UHD630 显卡就会不定时看心情死机，很无语😶 
* 如果不驱动 UHD630（让它显示7M显存）就不会死机，我甚至挂着电脑放了三个小时直播都不死机👍👍

### 电脑配置清单
* DeskMini 110
* 处理器：QNVH ```核显 UHD 630```
* 内存：海盗船 2133 8G + 三星 2400 8G
* 硬盘：SATA 固态 + SATA 机械盘 ```都试过安装 macOS```
* 显示器：惠普 24w 用的 HDMI
* BIOS：同款

### BIOS 频率和电压配置
* CPU 锁定 31 倍频
* CPU 电压 -50mV
* 核显限制电流 10A
* 核显电压 +50mV

在 Windows 里面怎么用都不会死机，可一到 macOS 里面就会随机死机了😰😰😰，试过这些：
* 安装 macOS Big Sur 11.5
* 安装 macOS Monterey 12.1
* 换 ig-platform-id
* 换 Open Core 版本 0.6.9, 0.7.2, 0.7.5, 0.7.6
* 按网上的打 FrameBuffer 补丁到 2048M
* 换其他网友的 EFI，换老哥的 EFI，自己用 OCAT 配置 EFI

反正试了好多😶 都还是一样的会不定时定格死机，只有让核显不工作的时候，就不死机了😭😭，感觉问题还是在核显电流电压上面😒

我是纯纯的萌新第一次装黑苹果，因为工作要用 Final Cut 还是想弄好，想请教老哥一些经验，谢谢老哥

**Comment by shum-elli** [comment]
之前我装这个的时候，在网上什么值得买里有个人说过，这台电脑的核显会有不定时死机 的情况，我现在也不用那台电脑的黑苹果，你可以参考一下的OC里面用的是哪一个核显的ID，因为这是8代笔记本的ES，我当时驱动的时候好像比较特殊，还有一点是你在bios里面有没有指定核显的显存大小，可能是溢出啥啥的，还有就是华擎这块板子在散热好电源充足的情况下，是可以上100w功率的，你试试不在bios里面对CPU的电压等进行限制，因为我记得bios里面降压之类的有的时候会失效，具体原因不清楚，我在bios里面修改的，在macos下面从来没生效过，具体什么问题我也不清楚，你试试在放开限制之后，在windows下是否会定时死机。
当然也有可能是ES体质的问题，因为macos对显卡的负载还是要大点的。我那块qnct放开限制，跑到100W（核显35W） 20分钟也不会死机，看贴吧和什么值得买有人说核显有15w功耗墙，我倒是觉得是不准确的。
总之，先修改显卡的那个id，排除oc问题，然后修改bios在macos和windows下轮流测试，最后就是换了哈哈

**Comment by ghost** [comment]
谢谢老哥提醒，换了一些 id 没效果，但是调核显电压会点用的样子。

只有设置核显电压 1.160V 才不会死机，但必须限制电流 8A，这样核显只有 330MHz 太低了 ……
然后发现 Windows 下面也会定格死机了，所以我愉快的决定，不弄了！

**Comment by ghost** [comment]
又试了几天，macos 下核显死机确实是和供电有关系。和 EFI 没有关系，现在用的老哥的 EFI 加了 Intel 无线网卡的驱动，用着挺好的，谢谢老哥。

H110 有一些电脑不会死机，我的也是刚刚买回来前两年不会死机，然后有一次重装 Windows 10 后就会死机了。然后死机一年比一年严重。后来换了 CPU 也一样的会死机，限制核显电流勉强能用一下。
* 2017年1月买的
* 2019年10月第一次死机
* 2020年春天只要玩英雄联盟就一定会死机
* 2020年秋天看B站都能死机
* 2021年春天进Windows过一会儿就会死机
* 2021年冬天有时候在Windows启动界面都会死机
* 2021年跨年Windows和macOS下都是进桌面就死机

昨天找我一个做维修的朋友问了一下，他说可能是充电器可能输出功率有问题导致的，然后我今天试着在 Monterey 中用 VoltageShift 限制 PL1 PL2 到 40W 跑了半个多小时，不但没有死机，而且 CPU 功耗从 48W 降低到了 31W。

我在外网上搜索了一下，发现 H110 和 X300 死机的最多，A300 死机的少一些而且死机的都是用的 3400G，H310 的死机的好像最少。这几个型号充电器都是 ADC027 120W 的。

我也从淘宝买了个新的 150W 充电器，看看换个充电器会不会好点。实在不行就换个新电脑吧，太烦人了。

**Comment by shum-elli** [comment]
我倒是之前好像也研究过电流的问题，之前烤鸡测试过，我那块U的话，在win下，用xtu细微改的话，跑满全核最低功耗好像就是差不多35w的样子，但是如果加上核显的话倒是要高不少，会上到55w的样子（intel的核显性能不强，吃电还挺厉害的），如果放开的话，我整U功耗上到过85，也能过半小时的烤鸡测试，我这台主机是去年年初的时候，闲鱼收的哈哈，电源也是ADC027，我觉得电源可能性其实也不大，一般不太会一个系列的电源都出问题，你这样子的话，那就可以试试降压锁频率呗哈哈，把cpu功耗给降下来呗哈哈    基本上降压然后核显不要开到最大频率，整U功耗做到40W以内还是没什么问题的。
我windows下倒是从来没遇到过死机的问题哈哈哈，可能我运气比较好吧
新年快乐咯~祝早日解决问题
我那台小主机现在也不怎么用哈哈哈  主力用的是10代I5的哈哈哈 准备寒假再折腾黑苹果

**Comment by ghost** [comment]
谢谢老哥的建议，我会去试试的，主要是想要个小点的电脑，不然我真的老早就换电脑了，太烦了。
祝2022新年快乐呀!

**Comment by ghost** [comment]
最新进展：换了个电源也还是死机，包括 Windows 里面。不想麻烦了，买了个联想 M710Q 准系统。
